### ISSUE TITLE
增加* 萬用字測試 最多頭4-5碼 可用*

### ISSUE THREAD

**Issue by deventw** [cyrus0880/rime-t9stroke#2]
你好，請問一下 萬用字*號 需要另外自行config 嗎？
G6按鍵排位中 * 對應的 “L” 沒有出現*的效果 
thx😃

**Comment by cyrus0880** [comment]
兩個版本萬用子測試還有點問提，因為RIME 官方文檔沒有詳細講解萬用字元用法，我還在想緊辦法

**Comment by cyrus0880** [comment]
我上傳了1.3 uiojk 版的修正版 
已修正萬用字測試  * 對應的 “L” 沒有出現的效果 的問題

**Comment by deventw** [comment]
> 我上傳了1.3 uiojk 版的修正版 已修正萬用字測試 * 對應的 “L” 沒有出現的效果 的問題

你好 剛剛嘗試了修正版
好像萬用字"L" 還是沒有生效
THX～

**Comment by deventw** [comment]
> > 我上傳了1.3 uiojk 版的修正版 已修正萬用字測試 * 對應的 “L” 沒有出現的效果 的問題
> 
> 你好 剛剛嘗試了修正版 好像萬用字"L" 還是沒有生效 THX～

有可能是 uiojk 中的dict字典有問題。THX
